#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import secrets

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
# we read a json stdin {"vars1":true, "var2":"foo", "vars3": 3} and we writ it to .config/state/environment
# Upper case to set environment variable and minor case to read from stdin



# Configure the application configurations
# Configure email configurations
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)

email_config  = {
    "MAIL_HOST": smtp_settings['host'],
    "MAIL_USERNAME": smtp_settings['username'],
    "MAIL_PASSWORD": smtp_settings['password'],
    "MAIL_PORT": smtp_settings['port'],
    "MAIL_SECURE": smtp_settings['encrypt_smtp'],
    "MAIL_FROM_NAME": data.get("MAIL_FROM_NAME", f"BigcapitalHQ {smtp_settings['username']}"),
    "MAIL_FROM_ADDRESS": data.get("MAIL_FROM_ADDRESS", f"{smtp_settings['username']}"),
}
agent.write_envfile('email.env', email_config)

HOST = data.get("host", "")
app_config = {
    "BASE_URL": "https://"+HOST,
    "NEW_RELIC_APP_NAME":"BIGCAPITALHQ",
    "NEW_RELIC_DISTRIBUTED_TRACING_ENABLED": "true",
    "NEW_RELIC_LOG": "stdout",
    "NEW_RELIC_AI_MONITORING_ENABLED": "true",
    "NEW_RELIC_CUSTOM_INSIGHTS_EVENTS_MAX_SAMPLES_STORED": "1000",
    "NEW_RELIC_SPAN_EVENTS_MAX_SAMPLES_STORED": "1000",
    "NEW_RELIC_LICENSE_KEY": "dfwfweewfw22e2e",
    "GOTENBERG_URL": "http//gotenberg-app:3000",
    "GOTENBERG_DOCS_URL": "http//server:3000/public/",
    **email_config,
}
agent.write_envfile('app.env', app_config)

# Make sure everything is saved inside the environment file
# just before starting systemd unit
#agent.dump_env()
