#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
# we read a json stdin {"vars1":true, "var2":"foo", "vars3": 3} and we writ it to .config/state/environment
# Upper case to set environment variable and minor case to read from stdin

# Configure database configurations

MARIADB_DATABASE = data.get("MARIADB_DATABASE","bigcapitalhq")
MARIADB_USER = data.get("MARIADB_USER","bigcapital")
MARIADB_ROOT_PASSWORD = data.get("MARIADB_ROOT_PASSWORD","Bigcapital,1234")
MARIADB_AUTO_UPGRADE = data.get("MARIADB_AUTO_UPGRADE","1")
MARIADB_PASSWORD = data.get("MARIADB_PASSWORD","Bigcapital,1234")

db_config = {
    "MARIADB_DATABASE": MARIADB_DATABASE,
    "MARIADB_USER": MARIADB_USER,
    "MARIADB_ROOT_PASSWORD": f'{MARIADB_ROOT_PASSWORD}',
    "MARIADB_AUTO_UPGRADE": MARIADB_AUTO_UPGRADE,
    "MARIADB_PASSWORD": f'{MARIADB_PASSWORD}',
}
agent.write_envfile('database.env', db_config)


# Make sure everything is saved inside the environment file
# just before starting systemd unit
#agent.dump_env()
